shell = "fish"

[window]
opacity = 0.9

[font]
normal = { family = "UbuntuMono", style = "Regular"}
bold = { style = "Iold"}
italic = { style = "Italic"}
size = 18.0

[cursor.style]
shape = "underline"
blinking = "off"

# Colors (Molokai)

[colors.primary]
background = '#000a05'
foreground = '#e0ffe0'

[colors.bright]
black = '#555555'
blue = '#00afff'
cyan = '#51ceff'
green = '#b1e05f'
magenta = '#af87ff'
red = '#f6669d'
white = '#ffffff'
yellow = '#fff26d'

[colors.cursor]
cursor = '#bbbbbb'
text = '#ffffff'

[colors.normal]
black = '#121212'
blue = '#1080d0'
cyan = '#43a8d0'
green = '#98e123'
magenta = '#8700ff'
red = '#fa2573'
white = '#bbbbbb'
yellow = '#dfd460'

[colors.selection]
background = '#b5d5ff'
text = '#000000'

# #Monokai
# [colors.primary]
# # background = "#272822"
# # foreground = "#f8f8f2"
# background = "#000a05"
# foreground = "#9acd32"
# # foreground = "#ccffcc"

# [colors.normal]
# black = "#272822"
# red = "#f92672"
# green = "#a6e22e"
# yellow = "#f4bf75"
# blue = "#66d9ef"
# magenta = "#ae81ff"
# cyan = "#a1efe4"
# white = "#f8f8f2"

# [colors.bright]
# black = "#75715e"
# red = "#f92672"
# green = "#a6e22e"
# yellow = "#f4bf75"
# blue = "#66d9ef"
# magenta = "#ae81ff"
# cyan = "#a1efe4"
# white = "#f9f8f5"
